name: "Rust Test"

# Trigger the workflow on push to master or pull request
"on":
  push:
    branches:
    - master
  pull_request:


jobs:
  rust_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable

    - name: Cargo test
      run: cargo test


