name: "Rust Miri"

# Trigger the workflow on push to master or pull request
"on":
  push:
  pull_request:

jobs:
  miri_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly

    - name: Install miri
      run: rustup +nightly component add miri

    - name: Cargo clean
      run: cargo clean

    - name: Miri test
      run: cargo +nightly miri test


